# Site settings
title: Filippo Aleotti
email: filippoaleotti@yahoo.it
url: https://example.github.io
description: "PhD student"
keywords: "your keywords, separated by commas"
skills: ""
meta_author: Aleotti Filippo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1b262c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: ff5151 #FD6E8A
  secondary-dark: 233140 #A2122F
  tertiary: ffa41b

# Footer settings
footer:
  copyright: Filippo Aleotti <br><br> Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>. 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: goole scholar
    url: https://scholar.google.com/citations?user=XN0qbX8AAAAJ&hl=it&oi=ao
  - title: github
    url: http://github.com/FilippoAleotti
  - tile: linkedin
    url: https://it.linkedin.com/in/filippo-aleotti-756886119

# Postal address (add as many lines as necessary)
address:


# Credits content
credits: 

# Build settings
markdown: kramdown
permalink: pretty
